### ISSUE TITLE
Nie działa

### ISSUE THREAD

**Issue by bayont** [AnakinM/JAZ#1]
Kod nie działa pomocy

**Comment by AnakinM** [comment]
Specjalnie dla Ciebie zupdatowałem readme xD
https://github.com/AnakinM/JAZ/blob/main/README.md

> I do not provide any additional support for this repository. If it does not work for you, figure it out yourself.

**Comment by bayont** [comment]
![71bc1012078_dzieki](https://github.com/AnakinM/JAZ/assets/25829941/8b96292a-6dda-4a2d-84a1-980ed67ba13a)
